### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Zumbalamambo** [shinsumicco/socket.io-client-cpp#1]
How to install this in windows 10?

**Comment by chyohoo** [comment]
cd /path/to/working/dir
git clone https://github.com/shinsumicco/socket.io-client-cpp
cd socket.io-client-cpp
git submodule init
git submodule update
mkdir build && cd build
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DBUILD_UNIT_TESTS=OFF \
    ..
make -j4
make install

**Comment by shinsumicco** [comment]
Please reopen this issue if you haven't solved, @Zumbalamambo.
