### ISSUE TITLE
Changes of this fork?

### ISSUE THREAD

**Issue by alessandroTorresani** [shinsumicco/socket.io-client-cpp#2]
Good morning Shinsumicco,
thank you for sharing this code. 

I was wondering what are the main differences of your fork with respect to the original socket-io repository. It is not clear from the README, it seems to me that you removed the boost dependencies. Are there any other differences?

Thank you in advance.

Alessandro

**Comment by shinsumicco** [comment]
@alessandroTorresani 
I've applied the following changes:

- Remove boost dependencies
- Use the newer versions of submodules
- Refactor CMake scripts in order to build the lib on Windows environments
- Add CI configuration

Any other questions?

**Comment by alessandroTorresani** [comment]
Everything clear, thank you very much.  

I found this repository thanks to OPEN-V-SLAM, I think it's a very nice idea to use a web visualization to display the SLAM output. Great job!
